[project]
name = "conda-recipe-v2-schema"
authors = ["Bas Zalmstra <zalmstra.bas@gmail.com>"]
channels = ["conda-forge"]
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]

[pypi-dependencies]
conda-recipe-v2-schema = { path = ".", editable = true }

[dependencies]
ruff = ">=0.5.2,<0.6"
pyyaml = ">=6.0.1,<7"
jsonschema = ">=4.23.0,<5"
pytest = ">=8.3.1,<9"

[tasks]
generate = "python conda_recipe_v2_schema/model.py > schema.json"
fmt = "ruff format ."
lint = "ruff check . --fix"
tests = "pytest tests"

[feature.py312.dependencies]
python = "3.12.*"

[feature.py311.dependencies]
python = "3.11.*"

[feature.py310.dependencies]
python = "3.10.*"

[feature.py39.dependencies]
python = "3.9.*"

[feature.py38.dependencies]
python = "3.8.*"

[environments]
default = { features = ["py312"], solve-group = "py312" }
py312 = { features = ["py312"], solve-group = "py312" }
py311 = ["py311"]
py310 = ["py310"]
py39 = ["py39"]
py38 = ["py38"]
